new_system/app/views/admin_view.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from app.lib.db_operation import *
from app.lib.utils import GetEnv, intel_sort, update_info_screen, export_events
import json
from werkzeug.utils import secure_filename
import requests


admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/admin/', methods=['GET'])
def admin_home():
    return home_tab()

@admin_bp.route('/admin/<string:tab_name>', methods=['GET','POST'])
def admin(tab_name):
    if tab_name == 'home':
        return home_tab()
    elif tab_name == 'global-config':
        return global_config_tab()
    elif tab_name == 's_set_active_driver':
        return s_set_active_driver()
    elif tab_name == 'cross_config':
        return cross_config_tab()
    elif tab_name == 'infoscreen':
        return infoscreen()
    elif tab_name == 'active_events':
        return active_events()
    elif tab_name == 'active_events_driver_data':
        return active_events_driver_data()
    elif tab_name == 'msport_proxy':
        return msport_proxy()
    elif tab_name == 'export':
        return export_data()
    elif tab_name == 'clock_mgnt':
        return clock_mgnt()
    elif tab_name == 'time_keeper':
        return timekeeperpage()
    elif tab_name == 'ledpanel':
        return led_panel()
    elif tab_name == 'kvali_criteria':
        return kvali_criteria()
    else:
        return "Invalid tab", 404



def s_set_active_driver():
    from flask import current_app
    list_address = current_app.config['listen_address']

    DB_PATH = "site.db"
    if request.method == "POST":
        active_driver_id = request.json["driverId"]
        with sqlite3.connect(DB_PATH) as con:
            cur = con.cursor()
            cur.execute("UPDATE active_drivers SET D1 = ?;", (active_driver_id,))
            print(cur.execute("SELECT * FROM active_drivers").fetchall())

        requests.get("http://{0}:7777/api/active_event_update".format(list_address))

        con.commit()
        return {"synced":"True"}

    return render_template('admin/s_set_active_driver.html') 

def home_tab():
    from app.models import ActiveDrivers, ActiveEvents, Session_Race_Records, GlobalConfig, MicroServices, archive_server
    from app import db
    from sqlalchemy import func
    import json

    archive_params = archive_server.query.first()

    archive_params_json = {"password": archive_params.auth_token, "hostname": archive_params.hostname, "enabled": archive_params.enabled}

    g_conf = db.session.query(GlobalConfig.db_location, GlobalConfig.event_dir, GlobalConfig.use_intermediate, GlobalConfig.intermediate_path).all()[0]

    db_location = g_conf[0]
    mount_path = g_conf[1]
    use_inter = g_conf[2]
    intermediate_path = g_conf[3]

    mount_bool = os.path.ismount(mount_path)

    if mount_bool == False:
        mount_bool = str(2)
    else:
        if use_inter == True:
            inter_files = g_conf[3]
            dir = os.listdir(inter_files)

            if len(dir) == 0: 
                mount_bool = str(3)
            else:
                mount_bool = str(1)
        else:
            mount_bool = str(1)

    # Query to get distinct event names and their counts
    enabled_events = (ActiveEvents.query
                        .filter(ActiveEvents.enabled == 1)
                        .group_by(ActiveEvents.event_name)
                        .with_entities(ActiveEvents.event_name, func.count(ActiveEvents.event_name))
                        .count())

    drivers = (Session_Race_Records.query
                      .with_entities(Session_Race_Records.first_name, Session_Race_Records.last_name)
                      .group_by(Session_Race_Records.first_name, Session_Race_Records.last_name)
                      .count())

    services = (MicroServices.query.all())
    

    number_runs = (ActiveEvents.query.filter(ActiveEvents.enabled == 1).count())

    unique_events = (
        db.session.query(
            ActiveEvents.event_name,
            func.max(ActiveEvents.run).label('max_run'),
            ActiveEvents.event_file
        )
        .group_by(ActiveEvents.event_name).order_by(ActiveEvents.sort_order)
        .all()
    )

    if request.method == "POST":

        if "endpoint_server_update" in request.form:

            hostname = request.form.get('hostname')
            password = request.form.get('password')
            state = request.form.get('state')

            if password == "":
                token = False
            else:
                token = True

            archive_params = archive_server.query.first()

            if state == "none":
                archive_params.hostname = hostname
                archive_params.auth_token = password
                archive_params.use_use_token = token
                db.session.commit()
            else:
                if state == "start":
                    state = True
                else:
                    state = False
                archive_params.hostname = hostname
                archive_params.auth_token = password
                archive_params.use_use_token = token
                archive_params.enabled = state

                db.session.commit()

            return {"Success":"Updated configuration"}
        
        elif "single_event" in request.form:
            
            if request.form.get('event_file') == "active_event":
                active_event = get_active_event()
                selectedEventFile = active_event[0]["db_file"]
                selectedRun = active_event[0]["SPESIFIC_HEAT"]
            else:
                selectedEventFile = request.form.get('single_event')
                
                sync_state = request.form.get('sync')

            if sync_state == "true":
                from app.lib.utils import GetEnv
                g_config = GetEnv()

                event_name = request.form.get('event_name')

                #Delete local driver session entries for the spesific event
                db.session.query(Session_Race_Records).filter((Session_Race_Records.title_1 + " " + Session_Race_Records.title_2)==event_name).delete()
                db.session.commit()
                print(selectedEventFile)
                full_db_reload(add_intel_sort=False, Event=selectedEventFile)


            print("Getting:", selectedEventFile)

            with sqlite3.connect(db_location + selectedEventFile + ".sqlite") as con:
                cur = con.cursor()
                cur.execute(f"SELECT COUNT() FROM drivers;")
                amount_drivers = cur.fetchone()
                cur.execute(f"SELECT COUNT() FROM sqlite_master WHERE type='table' AND name LIKE 'driver\_%' ESCAPE '\\';")
                heat_num = cur.fetchone()[0]
                valid_recorded_times = 0
                invalid_recorded_times = 0
                drivers_left = 0
 
                for a in range(1,heat_num+1):
                    cur.execute("SELECT COUNT() FROM driver_stats_r{0} WHERE FINISHTIME != 0 AND PENELTY = 0;".format(a))
                    valid_recorded_times += cur.fetchone()[0]

                    cur.execute("SELECT COUNT() FROM driver_stats_r{0} WHERE PENELTY != 0;".format(a))
                    invalid_recorded_times += cur.fetchone()[0]

                    cur.execute("SELECT COUNT() FROM driver_stats_r{0} WHERE FINISHTIME = 0 AND PENELTY = 0;".format(a))
                    drivers_left += cur.fetchone()[0]

                event_config = {"all_records":(valid_recorded_times + invalid_recorded_times + drivers_left), "p_times":invalid_recorded_times, "v_times":valid_recorded_times, "l_times":drivers_left, "drivers":amount_drivers, "heats":heat_num}
                return event_config
            
        elif "service_state" in request.form:
            from app.lib.utils import GetEnv, is_screen_session_running, manage_process_screen
            
            from time import sleep

            service_name = request.form.get('service_name')
            service_state = request.form.get('service_state')
            params = request.form.get('ip_address')

            if service_name == None:
                return "None"

            service_object = db.session.query(MicroServices).filter((MicroServices.name == service_name)).first()
            if service_object is not None:
                
                if bool(service_object.state) == False and service_state == "start":
                    service_object.state = True

                    if params != None:
                        service_object.params = params
                    db.session.commit()
                    manage_process_screen(service_object.path, "start")
                    sleep(1)

                    if is_screen_session_running(service_object.path) == True:
                        return "True"
                    else:
                        return "False"
                    
                elif bool(service_object.state) == True and service_state == "stop":
                    service_object.state = False
                    db.session.commit()

                    manage_process_screen(service_object.path, "stop")
                    sleep(1)
                    if is_screen_session_running(service_object.path) == False:
                        return "True"
                    else:
                        return "False"
                    
                elif bool(service_object.state) == True and service_state == "restart":
                    print("Restart")


    return render_template('admin/index.html', drivercount=drivers, num_run=number_runs, num_events=enabled_events, events=unique_events, microservices=services, mount_bool=mount_bool, mount_path=mount_path,  archive_params_json=archive_params_json)

def kvali_criteria():
    from app.models import EventKvaliRate
    from app import db

    
    if request.method == 'POST':
        data = request.get_json()
        EventKvaliRate.query.delete()
        data_len = len(data)

new_system/app/templates/active_events.html
{% extends 'layout.html' %}
{% block content %}

<style>
    .tabulator, .tabulator-header, .tabulator-tableHolder{
    overflow:visible !important;
}
</style>


    <h2>Event Setup</h2>

    <div id="example-table"></div>
    <link href="https://cdn.jsdelivr.net/npm/tabulator-tables@4.9.3/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/tabulator-tables@4.9.3/dist/js/tabulator.min.js"></script>
    <script>

document.addEventListener("DOMContentLoaded", function() {
    var updateButton = document.getElementById("update-button");
    if (updateButton) {
        updateButton.addEventListener("click", function() {
            var tableData = table.getData();
            tableData.forEach((row, index) => {
                row.sort_order = index;
            });
            document.getElementById("table-data").value = JSON.stringify(tableData);
        });
    } else {
        console.error("Element with ID 'update-button' not found.");
    }
});

        var tableData = [];
        
        {% for event in active_events %}
            console.log({{ event.enabled }})
            tableData.push({
                id: {{ event.id }},
                name: "{{ event.event_name }}",
                run: {{ event.run }},
                enable: {{ event.enabled }},
                sort_order: {{ event.sort_order }}
            });
        {% endfor %}


        var table = new Tabulator("#example-table", {
            data: tableData,
            layout: "fitColumns",
            responsiveLayout: "hide",
            tooltips: true,
            addRowPos: "top",
            history: true,
            pagination: "local",
            paginationSize: 99,
            movableRows: true,
            initialSort: [
                {column: "sort_order", dir: "asc"}
            ],
            columns: [
                {rowHandle: true, formatter: "handle", headerSort: false, frozen: true, width: 30, minWidth: 30},
                {title: "ORDER", field: "sort_order"},
                {title: "ID", field: "id"},
                {title: "Name", field: "name"},
                {title: "Run", field: "run"},
                {title: "Enabled", field: "enable", width: 90, hozAlign: "center", formatter: "tickCross", sorter: "boolean", editor: true},
            ],
        });
    </script>
<form id="update-form" method="post">
    <input type="hidden" id="table-data" name="table_data" value="">
    <button type="submit" id="update-button">Update</button>
</form>



{% endblock %}

new_system/app/templates/active_events_driver_data.html
{% extends 'layout.html' %}
{% block content %}

<link href="
https://cdn.jsdelivr.net/npm/tabulator-tables@5.5.2/dist/css/tabulator.min.css
" rel="stylesheet">

<script src="
https://cdn.jsdelivr.net/npm/tabulator-tables@5.5.2/dist/js/tabulator.min.js
"></script>

<h2>Event Setup</h2>

{{ event_entry_file }}

<form method="POST" action="{{ url_for('admin.admin', tab_name='active_events_driver_data') }}">
    <select id="eventDropdown" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="event_name">
        <option selected>Open this select menu</option>
        {% for event in unique_events %}
        <option value="{{ event[0] }}" data-run="{{ event[1] }}" data-event-file="{{ event[2] }}">{{ event[0] }}</option>
        {% endfor %}
    </select>

    <select id="runDropdown" class="form-select form-select-sm" aria-label=".form-select-sm example" name="run">
        <option selected>Open this select menu</option>
    </select>

    <input type="hidden" name="event_file" id="eventFileInput" value="">
<br>
    <div class="d-grid gap-2">
      <button class="btn btn-primary" type="submit">Select</button>
    </div>
</form>

<br>
<div id="driver-stats-table"></div>
<br>

<button id="updateData" class="btn btn-secondary">Update</button>
<button id="refresh_data" class="btn btn-secondary">Reload Event</button>

<script>
    var table;

    document.addEventListener("DOMContentLoaded", function(){

        table = new Tabulator("#driver-stats-table", {
            data: {{ sqldata|safe }},
            layout: "fitColumns",
            columns: [
                {title:"CID", field:"CID"},
                {title:"INTER_1", field:"INTER_1", editor:"input"},
                {title:"INTER_2", field:"INTER_2", editor:"input"},
                {title:"INTER_3", field:"INTER_3", editor:"input"},
                {title:"SPEED", field:"SPEED", editor:"input"},
                {title:"PENELTY", field:"PENELTY", editor:"input"},
                {title:"FINISHTIME", field:"FINISHTIME", editor:"input"},
                {title: "Locked", field: "LOCKED", width: 90, hozAlign: "center", formatter: "tickCross", sorter: "boolean", editor: true},
            ],
        });

    

document.getElementById("updateData").addEventListener("click", function() {
    if (!table) {
        console.error("Table is not initialized yet.");
        return;
    }

    var tableData = table.getData();

    var combinedData = {
        data: tableData,
        file: "{{ event_entry_file.file }}",
        run: "{{ event_entry_file.run }}"
    };

    var jsonData = JSON.stringify(combinedData);

     fetch("{{ url_for('admin.admin', tab_name='active_events_driver_data') }}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: jsonData
    }).then(response => response.json())
    .then(data => {
        console.log(data);
    });
});

document.getElementById("refresh_data").addEventListener("click", function() {
    if (!table) {
        console.error("Table is not initialized yet.");
        return;
    }

    var jsonData = {
        file: "{{ event_entry_file.file }}",
        run: "{{ event_entry_file.run }}"
    };
    
    console.log(jsonData)
     fetch("{{ url_for('api.api', tab_name='reload_event') }}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(jsonData),
    }).then(response => response.json())
    .then(data => {
        console.log(data);
    });
});

    });

    const eventDropdown = document.getElementById('eventDropdown');
    const runDropdown = document.getElementById('runDropdown');
    const eventFileInput = document.getElementById('eventFileInput');

    eventDropdown.addEventListener('change', function() {
        const selectedEvent = this.options[this.selectedIndex];
        const run = selectedEvent.getAttribute('data-run');
        const eventFile = selectedEvent.getAttribute('data-event-file');
        
        eventFileInput.value = eventFile;
        runDropdown.innerHTML = '';
        
        for (let i = 1; i <= run; i++) {
            const option = document.createElement('option');
            option.value = i;
            option.text = i;
            runDropdown.add(option);
        }
    });
</script>

{% endblock %}

new_system/app/templates/admin.html
{% extends 'layout.html' %}
{% block content %}
<h3>Global Config</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Parameter</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        {% for config in global_config %}
        <tr>
            <td>{{ config.param }}</td>
            <td>{{ config.value }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

new_system/app/templates/global_config.html
{% extends 'layout.html' %}
{% block content %}

  <script>
    function confirmAction() {
      return confirm("ALL CURRENT RACE DATA WILL BE RELOADED");
    }
  </script>

<h3>Global Config</h3>

<form method="post">
    {{ form.hidden_tag() }}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Parameter</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            {% for config in global_config %}

            <tr>
                <td>Session Name</td>
                <td>{{ form.session_name(value=config.session_name) }}</td>
            </tr>
            <tr>
                <td>Project Directory</td>
                <td>{{ form.project_dir(value=config.project_dir) }}</td>
            </tr>
            <tr>
                <td>Database location</td>
                <td>{{ form.db_location(value=config.db_location) }}</td>
            </tr>
            <tr>
                <td>Event Directory</td>
                <td>{{ form.event_dir(value=config.event_dir) }}</td>
            </tr>
            <tr>
                <td>Whitelist String</td>
                <td>{{ form.wl_title(value=config.wl_title) }}</td>
            </tr>
            <tr>
                <td>Use whitelist?</td>
                <td><input type="checkbox" name="wl_bool" {% if config.wl_bool %}checked{% endif %}></td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
    {{ form.submit() }}
    <input type="submit" name="reload" value="Reload" onclick="return confirmAction()">
</form>
{% endblock %}

new_system/app/templates/pdfconverter.html
{% extends 'layout.html' %}
{% block content %}
<h3>Global Config</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Parameter</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        {% for config in global_config %}
        <tr>
            <td>{{ config.param }}</td>
            <td>{{ config.value }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

new_system/app/templates/scores.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Flask App</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>
          .navbar-brand-flex {
            display: flex;
            align-items: center; /* this is optional, it vertically aligns the items in the middle */
        }
        img {
              margin-right: 10px;
        }

</style>
</head>
<body>
<div class="container">
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand navbar-brand-flex" href="#">
        <img src="{{ url_for('static', filename='img/logo.jpg') }}" width="40" height="40" class="d-inline-block align-top" alt="">
        <h4>Resultatliste</h4>
      </a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            All heats
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% for event in heats %}
                <button class="dropdown-item event-btn" data-event='{{ event | replace(" ", "") }}'>{{ event }}</button>
                {% endfor %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Event Sum
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% for event in events %}
                  <button class="dropdown-item event-btn" data-event='{{ event | replace(" ", "") }}'>{{ event }}</button>
                {% endfor %}
                
            </div>
          </li>
  <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  Current event
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <button class="dropdown-item current-event-btn">Show Current Event</button>
  </div>
</li>
        </ul>
        
      </div>
      
    </nav>

    <!-- Placeholder for event data -->
    <table id="event-data" class="table">
      <!-- Table headers -->
      <thead>
        <tr>
          <th>ID</th>
          <th>Navn</th>
          <th>Klubb</th>
          <th>Skuter</th>
          <th>Poeng</th>
          <th>Beste tid</th>
          <th>Status</th>
        </tr>
      </thead>
      <!-- Table body -->
      <tbody>
      </tbody>
    </table>
  </div>

  <!-- JQuery, Popper.js, and Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  <script>

$('.current-event-btn').click(function() {
    fetch(`http://192.168.1.50:8080/api/driver_data/current`)
        .then(response => response.json())
        .then(data => {

            $('#event-data tbody').empty();
            $('#event-data').prev('h4').remove();
             for(let eventKey in data){
                $('#event-data').before(`<h4>${eventKey}</h4>`)
                }
            Object.values(data).forEach(event => {
                Object.values(event).forEach(driver => {
                    const driverId = driver[0];
                    const driverName = driver[1] + " " + driver[2];
                    const driverClub = driver[3];
                    const driverVehicle = driver[4];
                    const driverPoints = driver[5][4];
                    const driverStatus = driver[6];
                    const driverBestTime = millisecondsToTime(driver[5][0]); // depending on where you have bestTime

                    const row = `
                      <tr>
                        <td>${driverId}</td>
                        <td>${driverName}</td>
                        <td>${driverClub}</td>
                        <td>${driverVehicle}</td>
                        <td>${driverPoints}</td>
                        <td>${driverBestTime}</td>
                        <td>${driverStatus}</td>
                      </tr>
                    `;
                    $('#event-data tbody').append(row);
                });
            });
        })
        .catch(error => console.error('Error:', error));
});

function millisecondsToTime(millis) {
    // Calculate minutes, seconds, and milliseconds
    let minutes = Math.floor(millis / 60000);
    let seconds = Math.floor((millis % 60000) / 1000); // Use Math.floor instead of Math.round
    let milliseconds = millis % 1000;

    // If seconds reach 60, increase minutes and reset seconds
    if (seconds === 60) {
        minutes += 1;
        seconds = 0;
    }

    // Format the minutes and seconds to always be two digits
    minutes = minutes.toString().padStart(2, '0');
    seconds = seconds.toString().padStart(2, '0');
    milliseconds = milliseconds.toString().padStart(3, '0');

    // Return formatted string
    return minutes + ":" + seconds + ":" + milliseconds;
}



    $('.event-btn').click(function() {
    const eventName = $(this).data('event');
    fetch(`http://192.168.1.50:8080/event/${eventName}`)
        .then(response => response.json())
        .then(data => {
            const summary = {};

            // Remove existing H2 title
            $('#event-data').prev('h4').remove();

            let minRun = Number.MAX_SAFE_INTEGER;
            let maxRun = Number.MIN_SAFE_INTEGER;
            let runPrefix = "";

            for(let run in data){
                console.log(run);

                // Parse the run number and the run name prefix (assumes " - Run " separator)
                let runParts = run.split(" - Run ");
                if (runParts.length === 2) {
                    runPrefix = runParts[0];
                    let runNumber = parseInt(runParts[1]);
                    if (runNumber < minRun) minRun = runNumber;
                    if (runNumber > maxRun) maxRun = runNumber;
                }

                for(let participant in data[run]){
                    const driver = data[run][participant];
                    const driverId = driver[0];
                    const driverName = driver[1] + ' ' + driver[2];
                    const driverClub = driver[3];
                    const driverVehicle = driver[4];
                    const driverStatus = driver[6];
                    const drivertime = driver[5][0];
                    let points = driver[5][4];
                    points = isNaN(points) ? 0 : points;

                    if(!summary[driverId]){
                        summary[driverId] = {
                            name: driverName,
                            vehicle: driverVehicle,
                            club: driverClub,
                            status: driverStatus,
                            time: [], // Change time to array
                            totalPoints: 0
                        }
                    }
                    summary[driverId].totalPoints += points;
                    summary[driverId].time.push(drivertime); // Push each timestamp
                }
            }

            // Add H2 title here
            let title = `${runPrefix} - Run ${minRun}`;
            if (maxRun > minRun) title += ` - ${maxRun}`;
            $('#event-data').before(`<h4>${title}</h4>`);

            $('#event-data tbody').empty();

            const sortedSummary = Object.entries(summary).sort((a, b) => {
                const pointDifference = b[1].totalPoints - a[1].totalPoints;
                if (pointDifference === 0) {
                    // If points are the same, sort by the best timestamp
                    const aTimes = a[1].time.filter(time => time !== 0);
                    const bTimes = b[1].time.filter(time => time !== 0);
                    const aBestTime = aTimes.length > 0 ? Math.min(...aTimes) : 0;
                    const bBestTime = bTimes.length > 0 ? Math.min(...bTimes) : 0;
                    return aBestTime - bBestTime;
                } else {
                    return pointDifference;
                }
            });

            for(let i = 0; i < sortedSummary.length; i++){
                const driverId = sortedSummary[i][0];
                const driver = sortedSummary[i][1];
                const times = driver.time.filter(time => time !== 0);
                const bestTime = times.length > 0 ? Math.min(...times) : 'N/A';
                const row = `
                  <tr>
                    <td>${driverId}</td>
                    <td>${driver.name}</td>
                    <td>${driver.club}</td>
                    <td>${driver.vehicle}</td>
                    <td>${driver.totalPoints}</td>
                    
                    <td>${millisecondsToTime(bestTime)}</td> 
                    <td>${driver.status}</td>
                  </tr>
                `;
                $('#event-data tbody').append(row);
            }
        })
        .catch(error => console.error('Error:', error));
});




</script>
</body>
</html>

new_system/app/templates/smb_config.html
{% extends 'layout.html' %}
{% block content %}
    <h2>Configure SMB Share</h2>
    <form action="" method="post">
        {% for config in smb_config %}
            {{ form.hidden_tag() }}
            <p>
                Enable {{ form.state(checked=config.state) }}  
            </p> 
            <p>
                {{ form.name.label }}<br>
                {{ form.name(value=config.name) }}
            </p>

            <p>
                {{ form.smb_path.label }}<br>
                {{ form.smb_path(value=config.smb_path) }}
            </p>
            <p>
                {{ form.smb_name.label }}<br>
                {{ form.smb_name(value=config.smb_name) }}
            </p>
            <p>
                {{ form.smb_port.label }}<br>
                {{ form.smb_port(value=config.smb_port) }}
            </p>
            <p>{{ form.submit() }}</p>
         {% endfor %}
    </form>
{% endblock %}