slide_app/slideshow/core/models.py
from slideshow.extensions import db


class Content(db.Model):
    path = db.Column(db.String(), primary_key=True)
    priority = db.Column(db.Integer, unique=True)
    type = db.Column(db.String(4))  # img, link, vid

    def __repr__(self):
        return f'{self.path}, {self.priority}'

slide_app/slideshow/core/views.py
from flask import render_template, request, redirect, url_for, flash, abort, \
    jsonify, Blueprint
from werkzeug.utils import secure_filename
from flask_login import login_required
import os

from config import upload_folder, allowed_extensions
from slideshow.extensions import db
from .models import Content

bp = Blueprint('core', __name__, template_folder='templates')

rotation_speed = 10000  # in miliseconds


def allowed_files(filename):
    return lambda f: '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extensions


@bp.errorhandler(500)
def custom_500(error: dict):
    response = jsonify({'message': error})


@bp.route('/remove_content', methods=['GET', 'POST'])
def remove_content():
    if request.method == 'POST':
        content_id = request.form.get('content_id')
        content = Content.query.filter_by(path=content_id)
        cont_object = content.first()

        if cont_object.type == 'file':
            os.remove(f'{upload_folder}/{cont_object.path}')
            content.delete()
        else:
            content.delete()
        db.session.commit()

    return redirect(url_for('core.setup'))


@bp.route('/alter_rotation_speed', methods=['GET', 'POST'])
def alter_rotation_speed():
    global rotation_speed

    try:
        rotation_speed = float(
            request.form.to_dict()['alter_rotation_speed']) * 1000
    except Exception as e:
        flash('Please enter a number')

    return redirect(url_for('core.setup'))


@bp.route('/upload_file', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        file = request.files.get('file')

        if 'file' not in request.files:
            return redirect(url_for('core.setup'))
        if file and allowed_files(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(upload_folder, filename))

            new_file = Content(type='file', path=filename)
            db.session.add(new_file)
            db.session.commit()
    else:
        abort(500, 'failed to upload file')

    return redirect(url_for('core.setup'))


@bp.route('/upload_link', methods=['GET', 'POST'])
def upload_link():
    if request.method == 'POST':
        path = request.form.to_dict()['upload_link']
        new_link = Content(type='link', path=path)
        db.session.add(new_link)
        db.session.commit()
    else:
        abort(500, 'failed to upload link')

    return redirect(url_for('core.setup'))


@bp.route('/')
#@login_required
def index():
    return render_template('index.html')


@bp.route('/login')
def login():
    return redirect(url_for('user.login'))


@bp.route('/register')
def register():
    return redirect(url_for('user.register'))


@bp.route('/setup')
#@login_required
def setup():
    global rotation_speed

    contents = Content.query.all()

    return render_template(
        'setup.html',
        contents=contents,
        rotation_speed=rotation_speed // 1000
    )


@bp.route('/slideshow')
def slideshow():
    images = [image for image in os.listdir(upload_folder) if image != '.gitkeep']
    links = db.session.query(Content).filter(Content.type == 'link')

    return render_template(
        'slideshow.html',
        images=images,
        links=[link.path for link in links],
        rotation_speed=rotation_speed,
    )

slide_app/slideshow/core/templates/index.html
{% extends 'layouts/base.html' %}


{% block content %}
    {% include 'macros/navbar.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">DS Slideshow</h1>
        <p class="lead">The fast, lightweight Digital Signage solution</p>
    </div>
    {% include 'macros/footer.html' %}
{% endblock %}

slide_app/slideshow/core/templates/setup.html
{% extends 'layouts/base.html' %}

{% block content %}
    <header>
        {% include 'macros/navbar.html' %}
    </header>

    <main>
        <div class="container">
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                            <div class='container form-group rounded'>
                                <form action='{{ url_for('core.upload_link') }}' method='POST'>
                                    <h3>Link</h3>
                                    <p class='text-muted'>
                                        Please enter the entire path to the page. e.g. https://google.co.uk. Note some
                                        pages will not work with this software.
                                    </p>

                                    <div class='d-flex'>
                                        <input type='text' id='upload_link' name='upload_link' class='form-control'
                                               autocomplete='off' placeholder='Enter link' required>
                                        <input type='submit' value='Add Link' formmethod='POST'
                                               class='ml-4 btn btn-primary'>
                                    </div>
                                </form>

                                <form type='file' method='POST' enctype='multipart/form-data'
                                      action="{{ url_for('core.upload_file') }}">
                                    <h3>Image</h3>
                                    <p class='text-muted'>Supported formats: .png .jpg .jpeg</p>

                                    <!-- Custom Bootstrap File Input -->
                                    <div class='d-flex'>
                                        <div class="custom-file">

                                            <input type="file" class="custom-file-input" id="file" name='file' required>
                                            <label class="custom-file-label" for="customFile">Choose file</label>
                                        </div>

                                        <input type='submit' value='Upload' formmethod='POST'
                                               class='ml-4 btn btn-primary'>
                                    </div>
                                </form>

                                <form class='mt-5' action='{{ url_for('core.alter_rotation_speed') }}' method='POST'>
                                    <h3>Slideshow Speed</h3>
                                    <p class='text-muted'>Current Speed: {{ rotation_speed | int }} seconds</p>

                                    <div class='d-flex'>
                                        <input type='text' id='alter_rotation_speed' name='alter_rotation_speed'
                                               class='form-control' autocomplete='off' placeholder='Speed (s)'
                                               required/>
                                        <input type='submit' value='Change Speed' formmethod='POST'
                                               class='ml-4 btn btn-primary'>
                                    </div>
                                </form>
                            </div>

                        </div>

                        <div class="modal-footer mt-5">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
                        </div>

                    </div>
                </div>
            </div>
            {% if contents %}
                <div class="album py-5 bg-light">

                <div class="container">
                    <button type="button" class="btn btn-primary ml-3" data-toggle="modal" data-target="#myModal">
                        Upload Content
                    </button>
                    <a href='/slideshow' class='btn btn-outline-secondary ml-3'>View Slideshow</a>

                <!-- Project Cards -->
                <div class="album py-5 bg-light">
                    <div class="container">

                        <h2 class='jumbotron-heading'>Content</h2>
                        <p class='text-muted'>Drag and drop slides to reorder the slideshow (not implemented yet)</p>
                        <hr>

                        <div class="row card-deck">
                            {% for content in contents %}
                                <div class="col-md-4 py-2">
                                    <div class="card mb-4 box-shadow h-100">
                                        {% if content.type == 'file' %}
                                            <img class="card-img-top"
                                                 src="{{ url_for('static', filename='images/slideshow_images/') }}{{ content.path }}"
                                                 alt="Card image cap" style='height: 50%; object-fit: cover'>
                                        {% elif content.type == 'link' %}
                                            <iframe class="card-img-top"
                                                    src="{{ content.path }}"
                                                    title="Card image cap"
                                                    style='height: 50%; object-fit: cover; border: 0;'></iframe>
                                        {% endif %}
                                        <div class="card-body">
                                            <hr>
                                            <p class="card-text text-muted">{{ content.path }}</p>
                                            <div style='width: 0; height: 0;'>
                                                <form id='{{ content.path }}'
                                                      action="{{ url_for('core.remove_content') }}"
                                                      method='POST'>
                                                    <input type='hidden' name='content_id' id='content_id'
                                                           value='{{ content.path }}'>
                                                </form>
                                            </div>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <div class="btn-group">
                                                    <button name='submit' value='{{ content.path }}' type='submit'
                                                            class='btn btn-sm btn-outline-secondary'>Settings
                                                    </button>
                                                    <button form='{{ content.path }}' type='submit'
                                                            class="btn btn-sm btn-outline-secondary">Remove
                                                    </button>
                                                </div>
                                                <p class='text-muted'>{{ rotation_speed | int }}s</p>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% else %}
                <div class='text-center mt-5'>
                    <h1>No Content to Display</h1>
                    <p class='text-muted'>Click below to begin adding content</p>
                    <button type="button" class="btn btn-primary ml-3" data-toggle="modal" data-target="#myModal">Upload
                        Content
                    </button>
                </div>
            {% endif %}
            </div>
    </main>

    {% include 'macros/footer.html' %}

{% endblock %}

{% block page_scripts %}
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
{% endblock %}

slide_app/slideshow/core/templates/slideshow.html
{% extends 'layouts/base.html' %}

{% block page_css %}
    <link rel='stylesheet' href='{{ url_for ('static', filename = 'css/indexFormatting.css') }}'>
{% endblock %}

{% block content %}
    {% if not links and not images %}
    <body class = 'not_found'>
        <div class = 'text-center'>
            <h2>No Content to Display</h2>
            <p>Please <a href='{{ url_for("core.setup") }}'>click here</a> to add content.</p>
        </div>
    </body>
    {% endif %}

    {% if links or images %}
        <div class='slideshowDiv'>
            {% for image in images %}
                <img class='slideshowContent'
                     src='{{ url_for('static', filename = 'images/slideshow_images/' + image) }}'>
            {% endfor %}

            {% for link in links %}
                <iframe src='{{ link }}' class='slideshowContent'></iframe>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% block page_scripts %}
    <script>
        var slideIndex = 0;
        var links =
        {{ links | safe}}
        var images =
        {{ images | safe }}

        if (images.length > 0 || links.length > 0) {
            carousel();
        } else {
            setTimeout(refreshPage, 5000);
        }

        function refreshPage() {
            location.reload(true);
        }

        function carousel() {
            var i;
            var x = document.getElementsByClassName('slideshowContent');
            for (i = 0; i < x.length; i++) {
                x[i].style.display = 'none';
            }

            slideIndex++;
            if (slideIndex > x.length) {
                slideIndex = 1;
                location.reload();
            }

            x[slideIndex - 1].style.display = 'block';
            setTimeout(carousel, {{ rotation_speed }});
        }
    </script>
{% endblock %}