slide_app/slideshow/core/views.py
from flask import render_template, request, redirect, url_for, flash, abort, \
    jsonify, Blueprint
from werkzeug.utils import secure_filename
from flask_login import login_required
import os

from config import upload_folder, allowed_extensions
from slideshow.extensions import db
from .models import Content

bp = Blueprint('core', __name__, template_folder='templates')

rotation_speed = 10000  # in miliseconds


def allowed_files(filename):
    return lambda f: '.' in filename and filename.rsplit('.', 1)[1].lower() in allowed_extensions


@bp.errorhandler(500)
def custom_500(error: dict):
    response = jsonify({'message': error})


@bp.route('/remove_content', methods=['GET', 'POST'])
def remove_content():
    if request.method == 'POST':
        content_id = request.form.get('content_id')
        content = Content.query.filter_by(path=content_id)
        cont_object = content.first()

        if cont_object.type == 'file':
            os.remove(f'{upload_folder}/{cont_object.path}')
            content.delete()
        else:
            content.delete()
        db.session.commit()

    return redirect(url_for('core.setup'))


@bp.route('/alter_rotation_speed', methods=['GET', 'POST'])
def alter_rotation_speed():
    global rotation_speed

    try:
        rotation_speed = float(
            request.form.to_dict()['alter_rotation_speed']) * 1000
    except Exception as e:
        flash('Please enter a number')

    return redirect(url_for('core.setup'))


@bp.route('/upload_file', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        file = request.files.get('file')

        if 'file' not in request.files:
            return redirect(url_for('core.setup'))
        if file and allowed_files(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(upload_folder, filename))

            new_file = Content(type='file', path=filename)
            db.session.add(new_file)
            db.session.commit()
    else:
        abort(500, 'failed to upload file')

    return redirect(url_for('core.setup'))


@bp.route('/upload_link', methods=['GET', 'POST'])
def upload_link():
    if request.method == 'POST':
        path = request.form.to_dict()['upload_link']
        new_link = Content(type='link', path=path)
        db.session.add(new_link)
        db.session.commit()
    else:
        abort(500, 'failed to upload link')

    return redirect(url_for('core.setup'))


@bp.route('/')
#@login_required
def index():
    return render_template('index.html')


@bp.route('/login')
def login():
    return redirect(url_for('user.login'))


@bp.route('/register')
def register():
    return redirect(url_for('user.register'))


@bp.route('/setup')
#@login_required
def setup():
    global rotation_speed

    contents = Content.query.all()

    return render_template(
        'setup.html',
        contents=contents,
        rotation_speed=rotation_speed // 1000
    )


@bp.route('/slideshow')
def slideshow():
    images = [image for image in os.listdir(upload_folder) if image != '.gitkeep']
    links = db.session.query(Content).filter(Content.type == 'link')

    return render_template(
        'slideshow.html',
        images=images,
        links=[link.path for link in links],
        rotation_speed=rotation_speed,
    )

slide_app/slideshow/user/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, request
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.security import generate_password_hash

from slideshow.extensions import db

from .forms import RegisterForm, LoginForm, EditProfileForm
from .models import User

bp = Blueprint('user', __name__, template_folder='templates', url_prefix='/user/')


@bp.errorhandler(500)
def custom_500(error: dict):
    response = jsonify({'message': error})

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is None or not user.check_password(form.password.data):
            flash('username or password incorrect', 'danger')
            return redirect(url_for('.login'))

        login_user(user, remember=form.remember.data)
        return redirect(url_for('core.setup'))

    return render_template('user/login.html', title='Login', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        u = User(username=form.username.data, email=form.email.data)
        u.gen_slug(form.username.data)
        u.hash_password(form.password.data)
        u.save()
        return redirect(url_for('user.login'))
    else:
        if hasattr(form, 'errors'):
            for key, value in form.errors.items():
                flash(value[0], 'warning')
                break

    return render_template('user/register.html', form=form)

@bp.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('core.index'))

@bp.route('/<username>', methods=['GET', 'POST'])
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    form = EditProfileForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.password = generate_password_hash(form.password.data)
        db.session.commit()

        flash('Your changes have been saved..', 'success')
        return redirect(url_for('.profile', username=current_user.username))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('user/profile.html', title='Profile', user=user, form=form)

@bp.route('/edit_profile', methods=['POST'])
@login_required
def edit_profile():
    pass

slide_app/slideshow/templates/macros/alerts.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

slide_app/slideshow/templates/macros/footer.html
<footer class='footer fixed-bottom'>
    <div class='container text-center'>
        <p class='text-muted'>Powered by DS Slideshow</p>
    </div>
</footer>

slide_app/slideshow/templates/macros/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('core.index') }}"><h3>DS Slideshow</h3></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('core.setup') }}" class="nav-link">
                        <i class="fas fa-cogs"></i>&ensp;Settings
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('user.profile', username=current_user.username) }}" class="nav-link">
                        <i class="fas fa-user-cog"></i>&nbsp;Profile
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('user.logout') }}" class="nav-link">
                        <i class="fas fa-sign-out-alt"></i>Sign&nbsp;Out
                    </a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fab fa-"></i>Documentation</a>
            </li>
            <li class="nav-item">
                <a class="nav-link fs-30 p-0" href="https://github.com/Digital-Signage-Slideshow/DS_Slideshow"
                   target="_blank"><i
                        class="fab fa-github"></i></a>
            </li>
        </ul>
    </div>
</nav>